# Custom configuration & aliases
alias vi="nvim"
alias svi='NVIM_APPNAME="svi" nvim'
alias ta="tmux attach"
alias hd="herdr"
alias ts='tmux new-session'
alias yz='yazi'
alias lg='lazygit'
alias ld='lazydocker'
alias agx='agy --dangerously-skip-permissions'
bindkey -s '^\' 'herdr-sessionizer\n'
